package com.nplekhanov.cars2.v2;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * @author nplekhanov
 */
public class Marks {
    private static Map<String,String> marks = new LinkedHashMap<>();
    static {
        marks.put("288", "ВАЗ (Lada)");
        marks.put("1", "AC");
        marks.put("5", "Acura");
        marks.put("12367128", "Adler");
        marks.put("7", "Alfa Romeo");
        marks.put("8", "Alpina");
        marks.put("11", "Aro");
        marks.put("12", "Asia");
        marks.put("14", "Aston Martin");
        marks.put("15", "Audi");
        marks.put("25", "Bentley");
        marks.put("30", "BMW");
        marks.put("2394", "Brabus");
        marks.put("671", "Brilliance");
        marks.put("36", "Bugatti");
        marks.put("37", "Buick");
        marks.put("40", "BYD");
        marks.put("2380", "Byvin");
        marks.put("41", "Cadillac");
        marks.put("45", "Caterham");
        marks.put("1284", "Changan");
        marks.put("646", "ChangFeng");
        marks.put("48", "Chery");
        marks.put("49", "Chevrolet");
        marks.put("50", "Chrysler");
        marks.put("52", "Citroen");
        marks.put("59", "Dacia");
        marks.put("60", "Dadi");
        marks.put("61", "Daewoo");
        marks.put("62", "DAF");
        marks.put("63", "Daihatsu");
        marks.put("64", "Daimler");
        marks.put("66", "Datsun");
        marks.put("68", "De Tomaso");
        marks.put("69", "Derways");
        marks.put("12383389", "DeSoto");
        marks.put("71", "Dodge");
        marks.put("597", "DongFeng");
        marks.put("72", "Doninvest");
        marks.put("74", "Eagle");
        marks.put("77", "FAW");
        marks.put("79", "Ferrari");
        marks.put("80", "Fiat");
        marks.put("2372", "Fisker");
        marks.put("82", "Ford");
        marks.put("588", "Foton");
        marks.put("88", "Geely");
        marks.put("90", "GMC");
        marks.put("95", "Great Wall");
        marks.put("573", "Hafei");
        marks.put("2040", "Haima");
        marks.put("2401", "Haval");
        marks.put("104", "Honda");
        marks.put("847", "HuangHai");
        marks.put("107", "Hummer");
        marks.put("109", "Hyundai");
        marks.put("114", "Infiniti");
        marks.put("112", "Iran Khodro");
        marks.put("121", "Isuzu");
        marks.put("122", "IVECO");
        marks.put("124", "JAC");
        marks.put("125", "Jaguar");
        marks.put("127", "Jeep");
        marks.put("1157", "JMC");
        marks.put("134", "Kia");
        marks.put("137", "Koenigsegg");
        marks.put("145", "Lamborghini");
        marks.put("146", "Lancia");
        marks.put("147", "Land Rover");
        marks.put("148", "Landwind");
        marks.put("152", "Lexus");
        marks.put("1627", "Liebao Motor");
        marks.put("645", "Lifan");
        marks.put("153", "Lincoln");
        marks.put("154", "Lotus");
        marks.put("2362", "Luxgen");
        marks.put("160", "Mahindra");
        marks.put("163", "Maruti");
        marks.put("164", "Maserati");
        marks.put("165", "Maybach");
        marks.put("166", "Mazda");
        marks.put("167", "McLaren");
        marks.put("170", "Mercedes-Benz");
        marks.put("171", "Mercury");
        marks.put("173", "Metrocab");
        marks.put("174", "MG");
        marks.put("177", "MINI");
        marks.put("181", "Mitsubishi");
        marks.put("182", "Mitsuoka");
        marks.put("185", "Morgan");
        marks.put("191", "Nissan");
        marks.put("196", "Oldsmobile");
        marks.put("197", "Opel");
        marks.put("205", "Peugeot");
        marks.put("490", "PGO");
        marks.put("491", "Piaggio");
        marks.put("206", "Plymouth");
        marks.put("207", "Pontiac");
        marks.put("208", "Porsche");
        marks.put("211", "Proton");
        marks.put("212", "PUCH");
        marks.put("217", "Renault");
        marks.put("219", "Rolls-Royce");
        marks.put("221", "Rover");
        marks.put("222", "Saab");
        marks.put("2347", "Santana");
        marks.put("226", "Saturn");
        marks.put("230", "Scion");
        marks.put("231", "SEAT");
        marks.put("236", "Skoda");
        marks.put("237", "Smart");
        marks.put("242", "Spyker");
        marks.put("243", "SsangYong");
        marks.put("246", "Subaru");
        marks.put("247", "Suzuki");
        marks.put("250", "Talbot");
        marks.put("251", "TATA");
        marks.put("252", "Tatra");
        marks.put("1689", "Tesla");
        marks.put("254", "Tianma");
        marks.put("255", "Tianye");
        marks.put("260", "Toyota");
        marks.put("261", "Trabant");
        marks.put("263", "Triumph");
        marks.put("273", "Volkswagen");
        marks.put("274", "Volvo");
        marks.put("534", "Vortex");
        marks.put("276", "Wartburg");
        marks.put("280", "Wiesmann");
        marks.put("12373638", "Willys");
        marks.put("282", "Xin Kai");
        marks.put("780", "ZX");
        marks.put("2390", "Бронто");
        marks.put("292", "ГАЗ");
        marks.put("296", "ЗАЗ");
        marks.put("297", "ЗИЛ");
        marks.put("299", "ИЖ");
        marks.put("301", "КамАЗ");
        marks.put("12384499", "Комбат");
        marks.put("311", "ЛуАЗ");
        marks.put("316", "Москвич");
        marks.put("232", "СеАЗ");
        marks.put("895", "СМЗ");
        marks.put("1038", "ТагАЗ");
        marks.put("336", "УАЗ");
        marks.put("1670", "Эксклюзив");
    }

    public static Map<String, String> getMarks() {
        return marks;
    }
}
