package com.nplekhanov.cars2.v2;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * @author nplekhanov
 */
public class Paths {
    private static final Map<String,String> paths = new LinkedHashMap<>();
    static {
        paths.put("Audi", "/cars/audi/all/");
        paths.put("BMW", "/cars/bmw/all/");
        paths.put("Cadillac", "/cars/cadillac/all/");
        paths.put("Chery", "/cars/chery/all/");
        paths.put("Chevrolet", "/cars/chevrolet/all/");
        paths.put("Chrysler", "/cars/chrysler/all/");
        paths.put("Citroen", "/cars/citroen/all/");
        paths.put("Daewoo", "/cars/daewoo/all/");
        paths.put("Dodge", "/cars/dodge/all/");
        paths.put("Fiat", "/cars/fiat/all/");
        paths.put("Ford", "/cars/ford/all/");
        paths.put("Great Wall", "/cars/great-wall/all/");
        paths.put("Honda", "/cars/honda/all/");
        paths.put("Hyundai", "/cars/hyundai/all/");
        paths.put("Infiniti", "/cars/infiniti/all/");
        paths.put("Jaguar", "/cars/jaguar/all/");
        paths.put("Jeep", "/cars/jeep/all/");
        paths.put("Kia", "/cars/kia/all/");
        paths.put("Land Rover", "/cars/land-rover/all/");
        paths.put("Lexus", "/cars/lexus/all/");
        paths.put("Lifan", "/cars/lifan/all/");
        paths.put("Mazda", "/cars/mazda/all/");
        paths.put("MINI", "/cars/mini/all/");
        paths.put("Mitsubishi", "/cars/mitsubishi/all/");
        paths.put("Nissan", "/cars/nissan/all/");
        paths.put("Opel", "/cars/opel/all/");
        paths.put("Peugeot", "/cars/peugeot/all/");
        paths.put("Porsche", "/cars/porsche/all/");
        paths.put("Renault", "/cars/renault/all/");
        paths.put("Saab", "/cars/saab/all/");
        paths.put("SEAT", "/cars/seat/all/");
        paths.put("Skoda", "/cars/skoda/all/");
        paths.put("SsangYong", "/cars/ssang-yong/all/");
        paths.put("Subaru", "/cars/subaru/all/");
        paths.put("Suzuki", "/cars/suzuki/all/");
        paths.put("Toyota", "/cars/toyota/all/");
        paths.put("Volkswagen", "/cars/volkswagen/all/");
        paths.put("Volvo", "/cars/volvo/all/");
        paths.put("ВАЗ (Lada)", "/cars/lada/all/");
        paths.put("ГАЗ", "/cars/gaz/all/");
        paths.put("ЗАЗ", "/cars/zaz/all/");
        paths.put("ТагАЗ", "/cars/tagaz/all/");
        paths.put("УАЗ", "/cars/uaz/all/");
        paths.put("AC", "/cars/ac/all/");
        paths.put("Acura", "/cars/acura/all/");
        paths.put("Adler", "/cars/adler/all/");
        paths.put("Alfa Romeo", "/cars/alfa-romeo/all/");
        paths.put("Alpina", "/cars/alpina/all/");
        paths.put("Alpine", "/cars/alpine/all/");
        paths.put("AM General", "/cars/am-general/all/");
        paths.put("Ariel", "/cars/ariel/all/");
        paths.put("Aro", "/cars/aro/all/");
        paths.put("Asia", "/cars/asia/all/");
        paths.put("Aston Martin", "/cars/aston-martin/all/");
        paths.put("Audi", "/cars/audi/all/");
        paths.put("Austin", "/cars/austin/all/");
        paths.put("Autobianchi", "/cars/autobianchi/all/");
        paths.put("Baltijas Dzips", "/cars/baltijas-dzips/all/");
        paths.put("Beijing", "/cars/beijing/all/");
        paths.put("Bentley", "/cars/bentley/all/");
        paths.put("Bertone", "/cars/bertone/all/");
        paths.put("Bitter", "/cars/bitter/all/");
        paths.put("BMW", "/cars/bmw/all/");
        paths.put("Borgward", "/cars/borgward/all/");
        paths.put("Brabus", "/cars/brabus/all/");
        paths.put("Brilliance", "/cars/brilliance/all/");
        paths.put("Bristol", "/cars/bristol/all/");
        paths.put("Bufori", "/cars/bufori/all/");
        paths.put("Bugatti", "/cars/bugatti/all/");
        paths.put("Buick", "/cars/buick/all/");
        paths.put("BYD", "/cars/byd/all/");
        paths.put("Byvin", "/cars/byvin/all/");
        paths.put("Cadillac", "/cars/cadillac/all/");
        paths.put("Callaway", "/cars/callaway/all/");
        paths.put("Carbodies", "/cars/carbodies/all/");
        paths.put("Caterham", "/cars/caterham/all/");
        paths.put("Changan", "/cars/changan/all/");
        paths.put("ChangFeng", "/cars/changfeng/all/");
        paths.put("Chery", "/cars/chery/all/");
        paths.put("Chevrolet", "/cars/chevrolet/all/");
        paths.put("Chrysler", "/cars/chrysler/all/");
        paths.put("Citroen", "/cars/citroen/all/");
        paths.put("Cizeta", "/cars/cizeta/all/");
        paths.put("Coggiola", "/cars/coggiola/all/");
        paths.put("Dacia", "/cars/dacia/all/");
        paths.put("Dadi", "/cars/dadi/all/");
        paths.put("Daewoo", "/cars/daewoo/all/");
        paths.put("DAF", "/cars/daf/all/");
        paths.put("Daihatsu", "/cars/daihatsu/all/");
        paths.put("Daimler", "/cars/daimler/all/");
        paths.put("Datsun", "/cars/datsun/all/");
        paths.put("De Tomaso", "/cars/de-tomaso/all/");
        paths.put("DeLorean", "/cars/delorean/all/");
        paths.put("Derways", "/cars/derways/all/");
        paths.put("DeSoto", "/cars/desoto/all/");
        paths.put("Dodge", "/cars/dodge/all/");
        paths.put("DongFeng", "/cars/dongfeng/all/");
        paths.put("Doninvest", "/cars/doninvest/all/");
        paths.put("Donkervoort", "/cars/donkervoort/all/");
        paths.put("DS", "/cars/ds/all/");
        paths.put("E-Car", "/cars/e-car/all/");
        paths.put("Eagle", "/cars/eagle/all/");
        paths.put("Eagle Cars", "/cars/eagle-cars/all/");
        paths.put("Ecomotors", "/cars/ecomotors/all/");
        paths.put("FAW", "/cars/faw/all/");
        paths.put("Ferrari", "/cars/ferrari/all/");
        paths.put("Fiat", "/cars/fiat/all/");
        paths.put("Fisker", "/cars/fisker/all/");
        paths.put("Ford", "/cars/ford/all/");
        paths.put("Foton", "/cars/foton/all/");
        paths.put("FSO", "/cars/fso/all/");
        paths.put("Fuqi", "/cars/fuqi/all/");
        paths.put("Geely", "/cars/geely/all/");
        paths.put("Geo", "/cars/geo/all/");
        paths.put("GMC", "/cars/gmc/all/");
        paths.put("Gonow", "/cars/gonow/all/");
        paths.put("Gordon", "/cars/gordon/all/");
        paths.put("Great Wall", "/cars/great-wall/all/");
        paths.put("Hafei", "/cars/hafei/all/");
        paths.put("Haima", "/cars/haima/all/");
        paths.put("Haval", "/cars/haval/all/");
        paths.put("Hawtai", "/cars/hawtai/all/");
        paths.put("Hindustan", "/cars/hindustan/all/");
        paths.put("Holden", "/cars/holden/all/");
        paths.put("Honda", "/cars/honda/all/");
        paths.put("HuangHai", "/cars/huanghai/all/");
        paths.put("Hummer", "/cars/hummer/all/");
        paths.put("Hyundai", "/cars/hyundai/all/");
        paths.put("Infiniti", "/cars/infiniti/all/");
        paths.put("Innocenti", "/cars/innocenti/all/");
        paths.put("Invicta", "/cars/invicta/all/");
        paths.put("Iran Khodro", "/cars/ikco/all/");
        paths.put("Isdera", "/cars/isdera/all/");
        paths.put("Isuzu", "/cars/isuzu/all/");
        paths.put("IVECO", "/cars/iveco/all/");
        paths.put("JAC", "/cars/jac/all/");
        paths.put("Jaguar", "/cars/jaguar/all/");
        paths.put("Jeep", "/cars/jeep/all/");
        paths.put("Jensen", "/cars/jensen/all/");
        paths.put("JMC", "/cars/jmc/all/");
        paths.put("Kia", "/cars/kia/all/");
        paths.put("Koenigsegg", "/cars/koenigsegg/all/");
        paths.put("KTM", "/cars/ktm/all/");
        paths.put("Lamborghini", "/cars/lamborghini/all/");
        paths.put("Lancia", "/cars/lancia/all/");
        paths.put("Land Rover", "/cars/land-rover/all/");
        paths.put("Landwind", "/cars/landwind/all/");
        paths.put("Lexus", "/cars/lexus/all/");
        paths.put("Liebao Motor", "/cars/liebao-motor/all/");
        paths.put("Lifan", "/cars/lifan/all/");
        paths.put("Lincoln", "/cars/lincoln/all/");
        paths.put("Lotus", "/cars/lotus/all/");
        paths.put("LTI", "/cars/lti/all/");
        paths.put("Luxgen", "/cars/luxgen/all/");
        paths.put("Mahindra", "/cars/mahindra/all/");
        paths.put("Marcos", "/cars/marcos/all/");
        paths.put("Marlin", "/cars/marlin/all/");
        paths.put("Marussia", "/cars/marussia/all/");
        paths.put("Maruti", "/cars/maruti/all/");
        paths.put("Maserati", "/cars/maserati/all/");
        paths.put("Maybach", "/cars/maybach/all/");
        paths.put("Mazda", "/cars/mazda/all/");
        paths.put("McLaren", "/cars/mclaren/all/");
        paths.put("Mega", "/cars/mega/all/");
        paths.put("Mercedes-Benz", "/cars/mercedes/all/");
        paths.put("Mercury", "/cars/mercury/all/");
        paths.put("Metrocab", "/cars/metrocab/all/");
        paths.put("MG", "/cars/mg/all/");
        paths.put("Microcar", "/cars/microcar/all/");
        paths.put("Minelli", "/cars/minelli/all/");
        paths.put("MINI", "/cars/mini/all/");
        paths.put("Mitsubishi", "/cars/mitsubishi/all/");
        paths.put("Mitsuoka", "/cars/mitsuoka/all/");
        paths.put("Morgan", "/cars/morgan/all/");
        paths.put("Morris", "/cars/morris/all/");
        paths.put("Nissan", "/cars/nissan/all/");
        paths.put("Noble", "/cars/noble/all/");
        paths.put("Oldsmobile", "/cars/oldsmobile/all/");
        paths.put("Opel", "/cars/opel/all/");
        paths.put("Osca", "/cars/osca/all/");
        paths.put("Packard", "/cars/packard/all/");
        paths.put("Pagani", "/cars/pagani/all/");
        paths.put("Panoz", "/cars/panoz/all/");
        paths.put("Perodua", "/cars/perodua/all/");
        paths.put("Peugeot", "/cars/peugeot/all/");
        paths.put("PGO", "/cars/pgo/all/");
        paths.put("Piaggio", "/cars/piaggio/all/");
        paths.put("Plymouth", "/cars/plymouth/all/");
        paths.put("Pontiac", "/cars/pontiac/all/");
        paths.put("Porsche", "/cars/porsche/all/");
        paths.put("Premier", "/cars/premier/all/");
        paths.put("Proton", "/cars/proton/all/");
        paths.put("PUCH", "/cars/puch/all/");
        paths.put("Puma", "/cars/puma/all/");
        paths.put("Qoros", "/cars/qoros/all/");
        paths.put("Qvale", "/cars/qvale/all/");
        paths.put("Reliant", "/cars/reliant/all/");
        paths.put("Renaissance", "/cars/renaissance/all/");
        paths.put("Renault", "/cars/renault/all/");
        paths.put("Renault Samsung", "/cars/renault-samsung/all/");
        paths.put("Rezvani", "/cars/rezvani/all/");
        paths.put("Rimac", "/cars/rimac/all/");
        paths.put("Rolls-Royce", "/cars/rolls-royce/all/");
        paths.put("Ronart", "/cars/ronart/all/");
        paths.put("Rover", "/cars/rover/all/");
        paths.put("Saab", "/cars/saab/all/");
        paths.put("Saleen", "/cars/saleen/all/");
        paths.put("Santana", "/cars/santana/all/");
        paths.put("Saturn", "/cars/saturn/all/");
        paths.put("Scion", "/cars/scion/all/");
        paths.put("SEAT", "/cars/seat/all/");
        paths.put("ShuangHuan", "/cars/shuanghuan/all/");
        paths.put("Skoda", "/cars/skoda/all/");
        paths.put("Smart", "/cars/smart/all/");
        paths.put("Soueast", "/cars/soueast/all/");
        paths.put("Spectre", "/cars/spectre/all/");
        paths.put("Spyker", "/cars/spyker/all/");
        paths.put("SsangYong", "/cars/ssang-yong/all/");
        paths.put("Subaru", "/cars/subaru/all/");
        paths.put("Suzuki", "/cars/suzuki/all/");
        paths.put("Talbot", "/cars/talbot/all/");
        paths.put("TATA", "/cars/tata/all/");
        paths.put("Tatra", "/cars/tatra/all/");
        paths.put("Tazzari", "/cars/tazzari/all/");
        paths.put("Tesla", "/cars/tesla/all/");
        paths.put("Tianma", "/cars/tianma/all/");
        paths.put("Tianye", "/cars/tianye/all/");
        paths.put("Tofas", "/cars/tofas/all/");
        paths.put("Toyota", "/cars/toyota/all/");
        paths.put("Trabant", "/cars/trabant/all/");
        paths.put("Tramontana", "/cars/tramontana/all/");
        paths.put("Triumph", "/cars/triumph/all/");
        paths.put("TVR", "/cars/tvr/all/");
        paths.put("Ultima", "/cars/ultima/all/");
        paths.put("Vauxhall", "/cars/vauxhall/all/");
        paths.put("Vector", "/cars/vector/all/");
        paths.put("Venturi", "/cars/venturi/all/");
        paths.put("Volkswagen", "/cars/volkswagen/all/");
        paths.put("Volvo", "/cars/volvo/all/");
        paths.put("Vortex", "/cars/vortex/all/");
        paths.put("Wartburg", "/cars/wartburg/all/");
        paths.put("Westfield", "/cars/westfield/all/");
        paths.put("Wiesmann", "/cars/wiesmann/all/");
        paths.put("Willys", "/cars/willis/all/");
        paths.put("Xin Kai", "/cars/xin-kai/all/");
        paths.put("Zastava", "/cars/zastava/all/");
        paths.put("Zenvo", "/cars/zenvo/all/");
        paths.put("Zotye", "/cars/zotye/all/");
        paths.put("ZX", "/cars/zx/all/");
        paths.put("Автокам", "/cars/avtokam/all/");
        paths.put("Астро", "/cars/astro/all/");
        paths.put("Бронто", "/cars/bronto/all/");
        paths.put("ВАЗ (Lada)", "/cars/lada/all/");
        paths.put("ГАЗ", "/cars/gaz/all/");
        paths.put("Ё-мобиль", "/cars/e-mobil/all/");
        paths.put("ЗАЗ", "/cars/zaz/all/");
        paths.put("ЗИЛ", "/cars/zil/all/");
        paths.put("ИЖ", "/cars/izh/all/");
        paths.put("КамАЗ", "/cars/kamaz/all/");
        paths.put("Канонир", "/cars/kanonir/all/");
        paths.put("Комбат", "/cars/kombat/all/");
        paths.put("ЛуАЗ", "/cars/luaz/all/");
        paths.put("Москвич", "/cars/moscvich/all/");
        paths.put("СеАЗ", "/cars/seaz/all/");
        paths.put("СМЗ", "/cars/smz/all/");
        paths.put("ТагАЗ", "/cars/tagaz/all/");
        paths.put("УАЗ", "/cars/uaz/all/");
        paths.put("Эксклюзив", "/cars/eksklyuziv/all/");
    }

    public static Map<String, String> getPaths() {
        return paths;
    }
}
