package com.nplekhanov.cars2.v2.moto;

import com.nplekhanov.cars2.v2.Mark;

import java.util.ArrayList;
import java.util.Collection;

/**
 * @author nplekhanov
 */
public class MotoMarks {
    public static Collection<Mark> getMarks() {
        Collection<Mark> marks = new ArrayList<>();
        marks.add(new Mark("741", "ABM"));
        marks.add(new Mark("1218", "American IronHorse"));
        marks.add(new Mark("1722", "Apollo"));
        marks.add(new Mark("354", "Aprilia"));
        marks.add(new Mark("1651", "Arlen Ness"));
        marks.add(new Mark("1323", "Armada"));
        marks.add(new Mark("1398", "Atlant"));
        marks.add(new Mark("3605", "Avantis"));
        marks.add(new Mark("362", "Bajaj"));
        marks.add(new Mark("3310", "Baltmotors"));
        marks.add(new Mark("3152", "Bars"));
        marks.add(new Mark("365", "Benelli"));
        marks.add(new Mark("367", "Beta"));
        marks.add(new Mark("1017", "Big Dog Motorcycles"));
        marks.add(new Mark("368", "Bimota"));
        marks.add(new Mark("1055", "Blata"));
        marks.add(new Mark("643", "BM"));
        marks.add(new Mark("30", "BMW"));
        marks.add(new Mark("642", "Boom Trikes"));
        marks.add(new Mark("372", "Boss Hoss"));
        marks.add(new Mark("374", "BRP"));
        marks.add(new Mark("375", "BSA"));
        marks.add(new Mark("1671", "BSE"));
        marks.add(new Mark("376", "Buell"));
        marks.add(new Mark("379", "Cagiva"));
        marks.add(new Mark("2039", "Campagna"));
        marks.add(new Mark("1057", "Can-Am"));
        marks.add(new Mark("1164", "Centurion"));
        marks.add(new Mark("1971", "CFMoto"));
        marks.add(new Mark("1379", "Cobra"));
        marks.add(new Mark("772", "Confederate"));
        marks.add(new Mark("385", "CPI"));
        marks.add(new Mark("2522", "CRZ"));
        marks.add(new Mark("388", "CZ"));
        marks.add(new Mark("389", "Daelim"));
        marks.add(new Mark("392", "Derbi"));
        marks.add(new Mark("2596", "Desert Raven"));
        marks.add(new Mark("395", "DKW"));
        marks.add(new Mark("396", "Dnepr (Днепр)"));
        marks.add(new Mark("625", "Ducar"));
        marks.add(new Mark("398", "Ducati"));
        marks.add(new Mark("2656", "Eurotex"));
        marks.add(new Mark("2988", "Excelsior-Henderson"));
        marks.add(new Mark("1313", "Falcon"));
        marks.add(new Mark("2303", "Fighter"));
        marks.add(new Mark("783", "Forsage"));
        marks.add(new Mark("415", "GAS GAS"));
        marks.add(new Mark("3092", "Genata"));
        marks.add(new Mark("1956", "Gryphon"));
        marks.add(new Mark("1474", "GX moto"));
        marks.add(new Mark("3823", "Hanway"));
        marks.add(new Mark("420", "Harley-Davidson"));
        marks.add(new Mark("423", "Highland"));
        marks.add(new Mark("104", "Honda"));
        marks.add(new Mark("655", "Honling"));
        marks.add(new Mark("425", "Husaberg"));
        marks.add(new Mark("426", "Husqvarna"));
        marks.add(new Mark("427", "Hyosung"));
        marks.add(new Mark("428", "Indian"));
        marks.add(new Mark("1248", "IRBIS"));
        marks.add(new Mark("2644", "Iron Eagle"));
        marks.add(new Mark("432", "Jawa"));
        marks.add(new Mark("434", "Jianshe-Yamaha"));
        marks.add(new Mark("1157", "JMC"));
        marks.add(new Mark("1574", "Johnny Pag"));
        marks.add(new Mark("442", "Kawasaki"));
        marks.add(new Mark("2402", "Kaxa Motos"));
        marks.add(new Mark("2640", "KAYO"));
        marks.add(new Mark("668", "Keeway"));
        marks.add(new Mark("447", "KTM"));
        marks.add(new Mark("448", "Kymco"));
        marks.add(new Mark("2147", "Legend"));
        marks.add(new Mark("645", "Lifan"));
        marks.add(new Mark("457", "Malaguti"));
        marks.add(new Mark("1069", "Mikilon"));
        marks.add(new Mark("470", "Minsk (Минск)"));
        marks.add(new Mark("474", "Moto Guzzi"));
        marks.add(new Mark("2954", "Motoland"));
        marks.add(new Mark("483", "MV Agusta"));
        marks.add(new Mark("484", "MZ"));
        marks.add(new Mark("1102", "Nexus"));
        marks.add(new Mark("1602", "Omaks Motors"));
        marks.add(new Mark("1071", "Orion"));
        marks.add(new Mark("488", "Pannonia"));
        marks.add(new Mark("664", "Patron"));
        marks.add(new Mark("3738", "PCW"));
        marks.add(new Mark("2129", "Pitmoto"));
        marks.add(new Mark("3210", "Pitrace"));
        marks.add(new Mark("1732", "Pitsterpro"));
        marks.add(new Mark("2696", "Pony Motors"));
        marks.add(new Mark("628", "QingQi"));
        marks.add(new Mark("1506", "Racer"));
        marks.add(new Mark("498", "Regal Raptor"));
        marks.add(new Mark("641", "Rewaco"));
        marks.add(new Mark("2316", "Rokon"));
        marks.add(new Mark("401", "Royal Enfield"));
        marks.add(new Mark("505", "Sachs"));
        marks.add(new Mark("1103", "Sagitta"));
        marks.add(new Mark("1784", "Saxon"));
        marks.add(new Mark("1079", "Senke"));
        marks.add(new Mark("512", "Sherco"));
        marks.add(new Mark("514", "Simson"));
        marks.add(new Mark("818", "Stels"));
        marks.add(new Mark("777", "Stingray"));
        marks.add(new Mark("247", "Suzuki"));
        marks.add(new Mark("519", "Sym"));
        marks.add(new Mark("257", "Titan"));
        marks.add(new Mark("3569", "Triketec"));
        marks.add(new Mark("263", "Triumph"));
        marks.add(new Mark("814", "TVS"));
        marks.add(new Mark("4182", "Upbeat (ABT)"));
        marks.add(new Mark("624", "Vento"));
        marks.add(new Mark("531", "Victory"));
        marks.add(new Mark("1435", "Viper"));
        marks.add(new Mark("3771", "Virus"));
        marks.add(new Mark("2694", "Wels"));
        marks.add(new Mark("1086", "Xmotos"));
        marks.add(new Mark("537", "Yamaha"));
        marks.add(new Mark("1621", "Yamasaki"));
        marks.add(new Mark("2594", "YCF"));
        marks.add(new Mark("735", "Zongshen"));
        marks.add(new Mark("3504", "Zontes"));
        marks.add(new Mark("540", "Zundapp"));
        marks.add(new Mark("546", "Восход"));
        marks.add(new Mark("3633", "Десна"));
        marks.add(new Mark("548", "ЗиД"));
        marks.add(new Mark("299", "ИЖ"));
        marks.add(new Mark("3390", "Китай (NoName)"));
        marks.add(new Mark("2298", "Ковровец"));
        marks.add(new Mark("315", "ММЗ"));
        marks.add(new Mark("526", "Тула"));
        marks.add(new Mark("340", "Урал"));
        marks.add(new Mark("1670", "Эксклюзив"));
        return marks;
    }
}
